name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Android Environment multi-command runner
      uses: giorgosneokleous93/docker-multicommand-android@v1.0.1
      with:
        command1: ./gradlew app:assembleDebug
